var avb=avb||{};avb.root=null;avb.section=null;avb.mode=null;avb.data={};avb.currentNode={};avb.firstYear=null;avb.lastYear=null;avb.currentYear=(new Date).getFullYear();avb.thisYear=avb.currentYear;avb.userContribution=null;avb.sections=["revenues","expenses","funds"];var timer=0;Number.prototype.px=function(){return this.toString()+"px"};function pushUrl(a,d,c,e){ie()||window.history.pushState({section:a,year:avb.thisYear,mode:c,nodeId:e},"","/"+a+"/"+avb.thisYear+"/"+c+"/"+e)}
function popUrl(a){ie()||null!==a.state&&(a.state.mode!==avb.mode?switchMode(a.state.mode,!1):avb.navigation.open(a.state.nodeId,!1))}function initialize(a){void 0!==a.year&&(!isNaN(parseInt(a.year))&&a.year<avb.lastYear&&a.year>avb.firstYear)&&(avb.thisYear=a.year);avb.section=a.section;$(".section").each(function(){$(this).text().toLowerCase()===avb.section.toLowerCase()&&$(this).addClass("selected")});avb.userContribution=avb.home.getContribution();setMode(a.mode);downloadData(avb.section)}
function downloadData(a){var d=[];$.each(avb.sections,function(a,e){d.push($.getJSON("/data/"+e+".json",function(a){avb.data[e]=a}))});$.when.apply($,d).done(function(){void 0!==a&&onDataload(avb.data[a])})}
function onDataload(a){avb.root=a;avb.firstYear=d3.min(avb.root.values,function(a){return a.year});avb.lastYear=d3.max(avb.root.values,function(a){return a.year});yearIndex=avb.thisYear-avb.firstYear;avb.navbar.initialize(avb.thisYear);avb.currentNode.data=void 0;avb.cards.initialize();avb.navigation.initialize(a);avb.navigation.open(avb.root.hash,!0);$("#searchbox").keyup(avb.navbar.searchChange);console.log("UI Loaded.")}
function updateSelection(a,d,c){avb.currentNode.data=a;avb.currentNode.year=d;avb.chart.update(a,c);avb.cards.update(a)}function setMode(a){var d=$("#avb-wrap"),c=$("#table-template"),e=$("#treemap-template");a&&"l"===a?(avb.navigation=avb.table,d.html(Mustache.render(c.html())),avb.mode="l"):(avb.navigation=avb.treemap,d.html(Mustache.render(e.html())),avb.mode="t")}
function switchMode(a,d){void 0===d&&(d=!0);setMode(a);d&&pushUrl(avb.section,avb.thisYear,a,avb.root.hash);onDataload(avb.data[avb.section])}function changeYear(a){a!==avb.thisYear&&(avb.currentNode=avb.root,pushUrl(avb.section,a,avb.mode,avb.root.hash),avb.thisYear=a,yearIndex=avb.thisYear-avb.firstYear,avb.navigation.update(avb.root),avb.navigation.open(avb.root.hash),$("#avb-home").is(":visible")&&avb.home.showGraph(100))}var log=function(a){console.log(a)};
function hexToRgb(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null}function mixrgb(a,d,c){return{r:Math.round(c*a.r+(1-c)*d.r),g:Math.round(c*a.g+(1-c)*d.g),b:Math.round(c*a.b+(1-c)*d.b)}}function translate(a,d,c){a.attr("transform","translate("+d.toString()+","+c.toString()+")")}function rotate(a,d){a.attr("transform","rotate("+d.toString()+" 100 100)")}
$.fn.center=function(){this.css("margin-top",Math.max(0,$(this).parent().height()-$(this).outerHeight())/2);return this};$.fn.availableHeight=function(){var a=$(this).height();$(this).children().each(function(){a-=$(this).outerHeight()});return Math.max(0,availableHeight)};$.fn.textfill=function(a,d){var c=10;for($(this).css({"font-size":c});$(this).width()<d&&c<a;)c+=1,$(this).css({"font-size":c});$(this).css({"font-size":c-1})};
function ie(){for(var a=3,d=document.createElement("div");d.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",d.getElementsByTagName("i")[0];);return 4<a?a:void 0}function capitalize(a){return a.charAt(0).toUpperCase()+a.slice(1)}window.onpopstate=popUrl;var fby=fby||[];(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.feedbackify.com/f.js";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(a,d)})();
var indexOf=function(a){indexOf="function"===typeof Array.prototype.indexOf?Array.prototype.indexOf:function(a){for(var c=-1,e,c=0;c<this.length;c++)if(this[c]===a){e=c;break}return e};return indexOf.call(this,a)},inArray=function(a,d){return-1<indexOf.call(a,d)};avb=avb||{};
avb.chart=function(){var a,d;initialize=function(c){void 0!==a&&a.remove();a=d3.select(c).append("svg");a.width=$(c).width();a.height=$(c).height();a.xmargin=50;a.ymargin=20;a.linestack=[];a.showLegend=!1;$("#info-wrap").click(toggleLegend);a.attr("height",a.height).attr("width",a.width);a.xscale=d3.scale.linear().domain([avb.firstYear,avb.lastYear]).range([a.xmargin,a.width-15]);a.layersWidth=a.xscale(avb.thisYear);addActions(a)};legend=function(c,d){a.legendLayers=c||a.legendLayers;a.legendParent=
d||a.legendParent;var b=[];a.legendLayers.each(function(c){b.push({key:c.key,color:d3.select(this).select("path").style("fill"),percentage:100*c.values[yearIndex].val/a.legendParent.values[yearIndex].val})});d3.selectAll("#legend tr").remove();var g=d3.select("#legend tbody").selectAll("tr").data(b.reverse()).enter().append("tr");g.append("td").append("div").classed("legend-label",!0).style("background-color",function(a){return a.color});g.append("td").text(function(a){return a.key+" ("+a.percentage.toFixed(2)+
"%)"});$("#legend").center()};initializeLayers=function(){setDatapointsVisibility();ie()||jQuery.browser.mobile||a.layersInitialized||(a.sideShadow=a.layerWindow.append("foreignObject").attr("width",10).attr("x",a.xscale.range()[1]-10).attr("height",a.yscale.range()[0]-10).attr("y",10).attr("class","foreignobj"),a.sideShadow.append("xhtml:div").style("width",(2).px()).style("height",(a.yscale.range()[0]-10).px()).classed("sideShadow",!0),a.layersInitialized=!0)};update=function(c,e){c=c||avb.currentNode.data;
e=e||avb.currentNode.color;void 0===a.axes&&(a.grids=a.append("g"),a.areagroup=a.append("g"),a.layers=a.append("g"),a.linegroup=a.append("g"),a.axes=a.append("g"),a.layerWindow=a.append("g"));d3.selectAll(a.grids.node().childNodes).remove();d3.selectAll(a.axes.node().childNodes).remove();a.yscale=d3.scale.linear().domain([0,1.2*d3.max(c.values,function(a){return a.val})]).range([a.height-a.ymargin,10]);var b=d3.svg.axis().scale(a.xscale).orient("bottom").tickSize(-a.yscale.range()[0]+10,0,0).ticks(6).tickFormat(function(a){return""});
a.grids.append("g").attr("class","multigrid").attr("transform","translate(0,"+a.yscale.range()[0]+")").call(b);b=d3.svg.axis().scale(a.yscale).orient("left").ticks(5).tickSize(-a.width+15+a.xmargin,0,0).tickFormat(function(a){return""});a.grids.append("g").attr("class","multigrid").attr("transform","translate("+a.xmargin+",0)").call(b);var b=d3.svg.line().interpolate("monotone").x(function(b){return a.xscale(b.year)}).y(function(b){return a.yscale(b.val)}),g=d3.svg.area().interpolate("monotone").x(function(b,
c){return a.xscale(b.year)}).y0(function(b){return a.height-a.ymargin}).y1(function(b){return a.yscale(b.val)}),f=avb.currentYear-avb.firstYear,h=0;if(void 0===a.visuals){a.visuals=[];for(i=0;2>i;i++)a.visuals.push(a.areagroup.append("svg:path"));for(i=0;2>i;i++)a.visuals.push(a.linegroup.append("svg:path"))}h=0;d3.selectAll("#areaclip").remove();a.append("g").append("clipPath").attr("id","areaclip").append("svg:path").attr("fill","none").attr("d",g(c.values.slice(0,c.values.length)));a.visuals[0].classed("area",
!0).transition().duration(h).attr("d",g(c.values.slice(0,c.values.length))).attr("fill","black");a.visuals[1].classed("area",!0).classed("projection",!0).transition().duration(h).attr("d",g(c.values.slice(f,c.values.length))).attr("color",e);a.visuals[0].style("fill",e);a.visuals[1].style("fill",e);a.visuals[2].classed("line",!0).transition().duration(h).attr("d",b(c.values.slice(0,f+1))).style("stroke",e);a.visuals[3].classed("line",!0).classed("projection",!0).transition().duration(h).attr("d",
b(c.values.slice(f,c.values.length))).style("stroke",e);b=d3.svg.axis().scale(a.xscale).orient("bottom").tickSize(0,0,0).tickPadding(10).tickFormat(function(a){return a});g=d3.svg.axis().scale(a.yscale).ticks(4).orient("left").tickSize(0,0,0).tickPadding(5).tickFormat(function(a){return formatcurrency(a)});void 0!==a.xAxisSocket&&(a.xAxisSocket.remove(),a.yAxisSocket.remove());void 0===a.circles&&(a.circles=a.linegroup.append("svg:g"),a.circles.selectAll("circle").data(c.values).enter().append("circle"));
a.circles.attr("data-name",c.key).selectAll("circle").data(c.values).attr("cx",function(b){return a.xscale(b.year)}).attr("cy",function(b){return a.yscale(b.val)}).attr("r",3).attr("stroke",e).attr("fill",e);a.circles.attr("data-name",c.key).selectAll("circle").data(c.values).enter().append("circle");f=a.axes.append("g").classed("overflows",!0);f.append("rect").attr("width",a.xmargin).attr("height",a.height);f.append("rect").attr("width",a.width).attr("height",a.ymargin).attr("y",a.height-a.ymargin);
f.append("rect").attr("width",10).attr("height",a.height).attr("x",a.xscale(avb.lastYear));a.xAxisSocket=a.axes.append("g").classed("axis",!0).classed("xAxis",!0).attr("transform","translate(0,"+(a.height-a.ymargin)+")").call(b);a.yAxisSocket=a.axes.append("g").attr("class","axis").attr("transform","translate( "+a.xmargin+",0)").call(g);$(".xAxis .tick:odd").each(function(){d3.select(this).classed("odd",!0)});d3.select(".xAxis g:nth-child("+(yearIndex+1)+")").classed("thisYear",!0);initializeLayers();
void 0!==d&&d.remove();drawLayers(c)};setDatapointsVisibility=function(){a.circles.selectAll("circle").attr("opacity",function(){var c=d3.select(this);parseFloat(c.attr("cx"))<a.layersWidth?c.style("opacity",0):c.style("opacity",1)})};toggleLegend=function(){a.showLegend=!a.showLegend;$("#legend-wrap, #cards").stop();a.showLegend?($("#legend-wrap").animate({left:"0"},350),$("#cards").animate({left:"100%"},350)):($("#legend-wrap").animate({left:"-100%"},350),$("#cards").animate({left:"0"},350))};slideLayers=
function(c){var d=Math.round(a.xscale.invert(c)),d=Math.max(d-avb.firstYear,0);yearIndex!==d&&(yearIndex=d,avb.cards.update(avb.currentNode.data),legend());c=Math.min(c,a.xscale.range()[1]);c=Math.max(c,a.xscale.range()[0]);a.layersWidth=c;a.layers.svg.attr("width",c);setDatapointsVisibility();ie()||jQuery.browser.mobile||a.layerLine.attr("x",c-10)};addActions=function(a){var d,b;function g(h){h=d3.event;h.preventDefault();k=!0;h="touchstart"===h.type?h.touches[0].pageX:h.offsetX||d3.mouse(this)[0];
slideLayers(h);b=a.layersWidth}function f(a){a=d3.event;a.preventDefault();k&&(dragging=!0,d=("touchmove"===a.type?a.touches[0].pageX:a.offsetX||d3.mouse(this)[0])-b,slideLayers(b+d))}function h(a){a=d3.event;a.preventDefault();k=!1}d=b=void 0;var k=!1;a.on("mousedown",g);a.on("mousemove",f);a.on("mouseup",h);a.on("touchstart",g);a.on("touchmove",f);a.on("touchend",h)};drawLayers=function(c,e){function b(b){ie()||jQuery.browser.mobile||(a.sideShadow.attr("clip-path","url(#areaclip)"),a.layerLine=
b.append("foreignObject").attr("x",a.layersWidth-10).attr("width",10).attr("y",10).attr("height",a.yscale.range()[0]-10).attr("class","foreignobj"),a.layerLine.append("xhtml:div").style("width",(3).px()).style("height",(a.yscale.range()[0]-10).px()).classed("layerLine",!0))}d=a.layers.append("svg").attr("height",a.height).attr("width",a.layersWidth).classed("layers",!0);d.attr("clip-path","url(#areaclip)");a.layers.svg=d;a.layers.classed("layers",!0);d.width=a.width;d.height=a.height;if(0===c.sub.length){b(d);
var g=a.areagroup.datum(c);legend(g,g.datum())}else{var f=a.yscale,h=a.xscale;d.xscale=h;d3.scale.category20();var k=d3.svg.area().interpolate("monotone").x(function(a){return h(a.year)}).y0(function(a){return f(a.y0)}).y1(function(a){return f(a.y0+a.val)}),l=d3.svg.line().interpolate("monotone").x(function(a){return h(a.year)}).y(function(a){return f(a.y0+a.val)}),g=d3.layout.stack().values(function(a){return a.values}).x(function(a){return a.year}).y(function(a){return a.val})(c.sub),g=d.selectAll(".browser").data(g).enter().append("g").attr("class",
"browser");d.areas=g.append("path").attr("class","multiarea").attr("d",function(a){return k(a.values)}).style("fill",function(a,b){return d3.scale.category20().range()[b%20]});d.lines=g.append("path").attr("class","multiline").attr("d",function(a){return l(a.values)}).style("stroke",function(a,b){return d3.scale.category20().range()[b%20]});legend(g,c);$(".layers g:last .multiline").remove();b(d)}};return{chart:a,initialize:initialize,update:update}}();stats={amount:{title:"Amount","class":"span6 top",value:function(a){return formatcurrency(a.values[yearIndex].val)},side:function(){return" in "+(avb.firstYear+yearIndex).toString()+"."},cellClass:"value sum ",cellFunction:function(a,d){avb.table.renderAmount(a,d)}},impact:{title:"Impact","class":"span6 ",value:function(a){return Math.max(0.01,Math.round(1E4*a.values[yearIndex].val/avb.root.values[yearIndex].val)/100).toString()+"%"},side:function(){return" of total "+avb.section+"."},cellClass:"value sum",
cellFunction:function(a,d){avb.table.renderImpact(a,d)}},individual:{title:"Individual","class":"span6 individual",value:function(a){log(yearIndex);return"$"+d3.round(avb.userContribution*(a.values[yearIndex].val/avb.root.values[yearIndex].val),2)},side:"your yearly contribution.",cellClass:"value sum",cellFunction:function(a,d){avb.table.renderImpact(a,d)}},growth:{title:"Growth","class":"span6 top",value:function(a){return growth(a)},side:" compared to previous year.",cellFunction:function(a,d){avb.table.renderGrowth(a,
d)},cellClass:"value"},source:{title:"Source","class":"span6 card-source ",value:function(a){return""===a.src?"Town of Arlington":a.src},link:function(a){return""===a.url?"http://www.town.arlington.ma.us/":a.url},side:"is the data source for this entry."},mean:{title:"Average","class":"span6 ",value:function(a){return formatcurrency(d3.mean(a.values,function(a){return a.val}))},side:"on average."},filler:{title:"","class":"span6 ",value:function(a){return""},side:""},name:{title:"Name",cellClass:"value name long textleft",
value:function(a){return a.key}},sparkline:{title:"Change",cellClass:"value sparkline",cellFunction:function(a,d){avb.table.renderSparkline(a,d)}},section:{title:"Type",cellClass:"value",value:function(a){return a.section}},parent:{title:"From",cellClass:"value",value:function(a){return"string"===typeof a.parent?a.parent:""}}};
decks={revenues:[stats.amount,stats.growth,stats.impact,stats.mean,stats.source],expenses:[stats.amount,stats.growth,stats.impact,stats.mean,stats.source],funds:[stats.amount,stats.growth,stats.impact,stats.mean,stats.source]};
tables={revenues:[stats.name,stats.growth,stats.sparkline,stats.impact,stats.amount],expenses:[stats.name,stats.growth,stats.sparkline,stats.impact,stats.amount],funds:[stats.name,stats.growth,stats.sparkline,stats.impact,stats.amount],search:[stats.name,stats.growth,stats.sparkline,stats.amount,stats.parent,stats.section]};
function formatcurrency(a){return void 0===a?"N/A":1E6<=a?"$"+Math.round(a/1E6).toString()+" M":1E6>a&&1E3<=a?"$"+Math.round(a/1E3).toString()+" K":1>a&&0!=a?"\u00a2"+Math.round(100*a).toString():"$ "+a.toString()}function formatCurrencyExact(a){return"$ "+d3.format(",.0f")(a)}function formatPercentage(a){return 0<a?"+ "+a.toString()+"%":0>a?"- "+Math.abs(a).toString()+"%":Math.abs(a).toString()+"%"}
function growth(a){a=Math.round(1E4*(a.values[yearIndex].val-(void 0!==a.values[yearIndex-1]?a.values[yearIndex-1].val:0))/a.values[yearIndex].val)/100;return formatPercentage(a)};avb=avb||{};
avb.treemap=function(){var a,d,c={r:255,b:255,g:255},e=function(b){a.selectAll("g").remove();var c=function(a){a.sub&&(f.nodes({values:a.values,children:a.sub}),a.sub.forEach(function(b){b.x=a.x+b.x*a.dx;b.y=a.y+b.y*a.dy;b.dx*=a.dx;b.dy*=a.dy;b.parent=a;c(b)}))},f=d3.layout.treemap().children(function(a,b){return b?null:a.children}).value(function(a){return a.values[yearIndex].val}).sort(function(a,b){return a.values[yearIndex].val-b.values[yearIndex].val}).ratio(0.5*(a.h/a.w)*(1+Math.sqrt(5))).round(!1);a.grandparent=
a.append("g").attr("class","grandparent");(function(b){b.x=b.y=0;b.dx=a.w;b.dy=a.h;b.depth=0})(b);c(b);d=display(b)};display=function(b){function c(a,b){b.selectAll(".child").data(function(a){return a.sub||[a]}).enter().append("g").attr("class","child").each(function(){var b=d3.select(this);void 0!==a.sub&&$.each(a.sub,function(){c(this,b)})}).append("rect").call(rect)}$(".no-value").popover("destroy");d3.format(",d");var f=a.insert("g",".grandparent").datum(b).attr("class","depth").on("click",function(a){zoneClick.call(this,
d3.select(this).datum(),!0)}).selectAll("g").data(0===b.sub.length?[b]:b.sub).enter().append("g");a.grandparent.datum(void 0===b.parent?b:b.parent).attr("nodeid",void 0===b.parent?b.hash:b.parent.hash).on("click",function(a){zoneClick.call(this,d3.select(this).datum(),!0)});updateTitle(b);f.filter(function(a){return a.sub}).classed("children",!0).on("click",function(a){zoneClick.call(this,d3.select(this).datum(),!0)}).each(function(){var a=d3.select(this);a.attr("nodeid",function(){return a.datum().hash})});
0!==b.sub.length&&void 0===b.color&&(b.color=a.color(0));for(var d=0;d<b.sub.length;d++)b.sub[d].color=a.color(d);f.append("rect").attr("class","parent").call(rect).style("fill",function(a){return background(a.color,0.8)});c(b,f);if(ie())return a.on("mouseout",function(){d3.select("#ie-popover").style("display","none")}),f;f.each(function(){d3.select(this).append("foreignObject").call(rect).attr("class","foreignobj").append("xhtml:div").html(function(a){var b='<div class="titleLabel">'+a.key+"</div>";
a='<div class="valueLabel">'+formatcurrency(a.values[yearIndex].val)+"</div>";return b+a}).attr("class","textdiv");textLabels.call(this)});return f};ieLabels=function(b){d3.select(this).append("text").call(rect).attr("dy","1.5em").attr("dx","0.5em").text(function(a){return a.key});textLabels.call(this);b=d3.select(this).datum();var c=a.y(b.y+b.dy)-a.y(b.y),f=a.x(b.x+b.dx)-a.x(b.x);if(40>c||150>f)d3.select(this).classed("no-label",!0),popover=!0;(function(a,b,c){d3.select(a).on("mouseover",function(){var a=
d3.select(this).select(".parent"),c=[parseFloat(a.attr("x")),parseFloat(a.attr("y"))],a=c[0]+parseFloat(a.attr("width"))/2-75;d3.select("#ie-popover").select(".text").text(b);d3.select("#ie-popover").style("display","block").style("left",a.px()).style("top",c[1].px())})})(this,b.key,b.descr)};textLabels=function(b){function c(a,d,f){$(a).find("div").first().popover({container:"body",trigger:"hover",placement:function(a,b){return 110>$(b).position().top?"left":"top"},title:""!==b.descr&&""!==b.title?
b.key:"",content:""!==b.descr?b.descr:b.key})}b=d3.select(this).datum();var f=a.y(b.y+b.dy)-a.y(b.y),d=a.x(b.x+b.dx)-a.x(b.x),e=$(this).find(".titleLabel").first(),l=$(this).find(".textdiv").first();$(this).find("div").first().popover("destroy");d3.select(this).classed("no-value",!1);d3.select(this).classed("no-label",!1);l.height(Math.max(0,f-16));var m=!1;if(f<e.outerHeight()||40>f||60>d)d3.select(this).classed("no-label",!0),m=!0;(f<l.height()||80>f||90>d)&&d3.select(this).classed("no-value",!0);
(m||""!==b.descr||80>d)&&c(this,b.key,b.descr)};updateTitle=function(a){var c=$(".title-head .text"),d=$("#zoombutton"),e=d3.select(".grandparent").node();d.unbind();c.text(a.key);c.textfill(48,$(".title-head").width()-120);inArray(avb.sections,a.key.toLowerCase())&&$('<div class="description">  </div>').appendTo(c).text(a.descr);avb.currentNode.data===avb.root?d.addClass("disabled"):d.removeClass("disabled");d.click(function(){zoneClick.call(e,d3.select(e).datum(),!0)})};open=function(a,c){var d=
d3.select('g[nodeid*="'+a+'"]');zoneClick.call(d.node(),d.datum(),c)};zoneClick=function(b,c){var f=window.event||f;f&&(f.cancelBubble=!0,f.stopPropagation&&f.stopPropagation());!a.transitioning&&(b&&avb.currentNode)&&(b!==avb.root&&b===avb.currentNode.data?$("#zoombutton").trigger("click"):(!0===c&&pushUrl(avb.section,avb.thisYear,avb.mode,b.hash),yearIndex=avb.thisYear-avb.firstYear,a.selectAll("text").remove(),updateSelection(b,yearIndex,b.color),a.transitioning=!0,d.selectAll(".parent").style("opacity",
1),f=display(b),t1=d.transition().duration(750),t2=f.transition().duration(750),a.x.domain([b.x,b.x+b.dx]),a.y.domain([b.y,b.y+b.dy]),a.style("shape-rendering",null),a.selectAll(".depth").sort(function(a,b){return a.depth-b.depth}),f.selectAll(".foreignobj").style("fill-opacity",0),t1.selectAll(".foreignobj").call(rect),t2.selectAll(".foreignobj").call(rect),t1.selectAll("rect").call(rect),t2.selectAll("rect").call(rect),t2.each(function(){ie()||textLabels.call(this)}),t2.each("end",function(){ie()?
ieLabels.call(this):textLabels.call(this)}),t1.remove().each("end",function(){a.style("shape-rendering","crispEdges");a.transitioning=!1}),d=f))};rect=function(b){b.attr("x",function(b){return a.x(b.x)}).attr("y",function(b){return a.y(b.y)}).attr("width",function(b){return a.x(b.x+b.dx)-a.x(b.x)}).attr("height",function(b){return a.y(b.y+b.dy)-a.y(b.y)})};background=function(a,d){var f=mixrgb(hexToRgb(a),c,d);return"rgba("+f.r+","+f.g+","+f.b+",1)"};return{initialize:function(b){var c=$("#navigation").width(),
d=$("#navigation").height(),h={top:0,right:0,bottom:0,left:0},d=d-h.top-h.bottom;d3.format(",d");a=d3.select("#navigation").append("svg").attr("width",c+h.left+h.right).attr("height",d+h.bottom+h.top).style("margin-left",-h.left+"px").style("margin.right",-h.right+"px").append("g").attr("transform","translate("+h.left+","+h.top+")").style("shape-rendering","crispEdges");a.x=d3.scale.linear().domain([0,c]).range([0,c]);a.y=d3.scale.linear().domain([0,d]).range([0,d]);a.h=d;a.w=c;a.m=h;a.color=d3.scale.category20();
$("#zoombutton").center();avb.chart.initialize("#chart");e(b)},update:e,open:open,updateTitle:updateTitle}}();avb=avb||{};
avb.cards=function(){var a=[],d=[];return{update:function(c){d3.select("#cardtitle").text(c.name+" in "+avb.thisYear.toString());for(var e=0;e<a.length;e++)d[e].html(Mustache.render($("#card-template").html(),a[e])),d[e].select(".cardvalue").html(a[e].value(c)),"function"===typeof a[e].link&&(d[e].attr("onclick","window.location='"+a[e].link(c)+"'"),$(d[e].node()).click(function(){var a=window.event||a;a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation())})),d[e].select(".carddesc").html("string"===typeof a[e].side?
a[e].side:a[e].side(c))},clear:function(){d.length=0},initialize:function(){d=[];a=decks[avb.section];for(var c,e=0;e<a.length;e++){0===e%2&&(c=d3.select("#cards").append("div").attr("class","row-fluid card-row separator"));var b=c.append("div").html(Mustache.render($("#card-template").html(),a[e]));d.push(b)}}}}();avb=avb||{};
avb.home=function(){var a={},d=[{selector:"#information-cards",text:"See the basic financial summary and high level data story.",position:"right"},{selector:"#chart-wrap",text:"Explore how the town revenues changed over time.",position:"right"},{selector:"#navigation",text:"The xray of the financials... Zoom into the data details by touching a block. How cool was that?",position:"left"},{selector:"#yeardrop",text:"Interested in seeing budget history or projections? Use this menu.",position:"left",before:function(){setTimeout(function(){$("#yeardrop-container").addClass("open")},
800)}}],c=[{selector:".individual",text:"Here is your yearly contribution.",position:"right"},{selector:"#navigation",text:"See how much you pay for these services.",position:"left"}],e=[{selector:"#fire",text:"The fire department accounts for one of the greatest town department expenses.",position:"left",before:function(){$('g[nodeid="bd2b7e5f"]').find("div").first().attr("id","fire")}},{selector:"#cards",text:"Here is the basic information you need to know about the department.",position:"down",
before:function(){avb.navigation.open("bd2b7e5f")}},{selector:"#zoombutton",text:"Go back and explore more.",position:"left"}],b=[{selector:"#snow",text:"Snow removal has a relatively small cost compared to other departments",position:"top",before:function(){$('g[nodeid="c61196eb"]').find("div").first().attr("id","snow")}},{selector:"#chart",text:"Check how the snow removal costs oscillate over the years.",position:"right",before:function(){avb.navigation.open("c61196eb")}},{selector:"#cards",text:"Here is the basic information about snow removal over the current year.",
position:"right"},{selector:"#zoombutton",text:"Go back and explore more.",position:"left"}],g=[{selector:"#school",text:"School play an important role in the town expenses.",position:"bottom",before:function(){$('g[nodeid="b5fe5259"]').find("div").first().attr("id","school")}},{selector:"#cards",text:"They constitute about 40% of the yearly expenses.",position:"right",before:function(){avb.navigation.open("b5fe5259")}},{selector:"#zoombutton",text:"Go back and explore more.",position:"left"}];init=
function(d){function h(a,b){sectionClick.call(this);setTimeout(function(){void 0!==b?(setTimeout(function(){b()},1E3),setTimeout(function(){starttour(a)},2500)):starttour(a)},500)}a.content=$("#avb-home");a.overlay=$("#overlay");a.map=$("#home-map-svg");a.menubar=$("#avb-menubar");a.overlay.click(function(a){a.stopPropagation();$($(".section").get(2)).addClass("selected");hide()});$(".section").removeAttr("onclick");$("#tax-input").val(getContribution());$("#tax-input-start").click(function(){setContribution();
h.call(this,c)});$("#tax-input").keypress(function(a){13==a.which&&(setContribution(),h.call(this,c))});$("#q1").click(function(){h.call(this,e,function(){avb.navigation.open("dc313bc5");e[0].before()})});$("#q2").click(function(){sectionClick.call(this);setTimeout(function(){g[0].before();starttour(g)},1200)});$("#q3").click(function(){h.call(this,b,function(){avb.navigation.open("dc313bc5");b[0].before()})})};sectionClick=function(){initialize({section:$(this).attr("data-section").toLowerCase()});
setTimeout(function(){hide()},100)};getContribution=function(){var a=jQuery.cookie("contribution")||null;null!==a&&decks.expenses[0].title!==stats.individual.title&&decks.expenses.unshift(stats.individual);return a};setContribution=function(){var a=parseFloat($("#tax-input").val());isNaN(a)||(avb.userContribution=a,jQuery.cookie("contribution",avb.userContribution,{expires:14}))};validate=function(a){a=a||window.event;var b=a.keyCode||a.which,b=String.fromCharCode(b);/[0-9]|\./.test(b)||(a.returnValue=
!1,a.preventDefault&&a.preventDefault())};showGraph=function(b){var c=a.data.sub,d=d3.scale.linear().clamp(!0).range([30,160]).domain([0,d3.max(c,function(a){return a.values[yearIndex].val})]);$("#revenues-node").animate({height:d(c[0].values[yearIndex].val)},b).find(".node-value").text(formatcurrency(c[0].values[yearIndex].val));$("#expenses-node").animate({height:d(c[1].values[yearIndex].val)},b).find(".node-value").text(formatcurrency(c[1].values[yearIndex].val));$("#funds-node").animate({height:d(c[2].values[yearIndex].val)},
b).find(".node-value").text(formatcurrency(c[2].values[yearIndex].val));$(".node-value").fadeIn(b);$(".node").click(sectionClick)};show=function(){a.menubar.removeClass("purple-border");a.content.show();a.overlay.show();$.getJSON("data/home.json",function(b){setTimeout(function(){a.data=b;showGraph(1E3)},1E3)});initialize({section:"funds"});$(".section").removeClass("selected")};hide=function(b){a.content.slideUp(function(){a.menubar.addClass("purple-border")});a.overlay.fadeOut(function(){(b||isFirstVisit())&&
starttour()})};isFirstVisit=function(){var a=jQuery.cookie("visited");jQuery.cookie("visited","y",{expires:14});return"y"!==a};starttour=function(b){b=b||d;(function(b){for(var c=0;c<b.length;c++)$(b[c].selector).attr("data-intro",b[c].text).attr("data-step",c+1).attr("data-position",b[c].position);a.selectedTour=b})(b);tour=introJs();tour.onchange(function(a){a=parseInt($(a).attr("data-step"))-1;a===b.length-1&&$(".introjs-nextbutton, .introjs-prevbutton").hide();"function"===typeof b[a].before&&
b[a].before()});tour.setOption("showStepNumbers",!1);tour.setOption("skipLabel","Exit");tour.start()};return{initialize:init,show:show,showGraph:showGraph,hide:hide,validate:validate,getContribution:getContribution,setContribution:setContribution}}();avb=avb||{};
avb.navbar=function(){var a=function(a){var e=[];$.each(avb.sections,function(){var b=this,g=d(a,avb.data[this],avb.data);$.each(g,function(){this.section=capitalize(b)});e=e.concat(g)});return e},d=function(a,e,b){var g=e.key.toLowerCase().indexOf(a.toLowerCase());0!==g&&" "!==e.key[g-1]&&(g=-1);-1!=g&&(e.parent=b.key);b=-1!==g?[e]:[];if(void 0!==e.sub)for(g=0;g<e.sub.length;g++)b=b.concat(d(a,e.sub[g],e));return b};return{initialize:function(){$dropdown=$("#yeardrop-container");$dropdownLabel=$("#yeardrop-label");
$dropdownList=$("#yeardrop-list");$selector=$("#yeardrop-container-mobile");if(jQuery.browser.mobile){$selector.html("");for(a=avb.firstYear;a<=avb.lastYear;a++)d="<option"+(a==avb.thisYear?' selected="selected"':" ")+'value="'+a+'">'+a+"</option>",$selector.append(d);$selector.change(function(){changeYear(parseInt($selector.val()))});$selector.show();$("#yeardrop").css({"vertical-align":"top"})}else{$dropdownList.html("");for(var a=avb.firstYear;a<=avb.lastYear;a++){var d='<li role="presentation"><a role="menuitem" tabindex="-1" href="#">'+
a+"</a></li>";$dropdownList.append(d);$dropdownList.find("li :last").click(function(a){a.preventDefault();a=parseInt($(this).text());$dropdownLabel.html(a+' <b class="caret"></b>');changeYear(a);$dropdown.removeClass("open")})}$dropdownLabel.html(avb.thisYear+' <b class="caret"></b>');$dropdown.show()}jQuery.browser.mobile&&($("#navbar-map").text("Map"),$("#navbar-table").text("Table"),$("#navbar-funds").text("Funds"));$("#searchbox").bind("click touchstart",function(){$("#avb-home").is(":visible")&&
avb.home.hide()})},searchChange:function(){var c=$(this).val();clearTimeout(timer);timer=setTimeout(function(){avb.navigation!==avb.table&&setMode("l");pushUrl(avb.section,avb.thisYear,"l",avb.root.hash);avb.navigation.initialize(a(c))},300)},minimize:function(){log($("#navbar-links .entry").last().remove())}}}();avb=avb||{};
avb.table=function(){var a=[],d=d3.scale.linear().clamp(!0).domain([-10,10]).range(["rgb(29,118,162)","rgb(167, 103, 108)"]),c=d3.scale.linear().clamp(!0).range(["#aaa","#333"]),e=d3.scale.linear().clamp(!0).domain([0,100]).range(["#aaa","#333"]),b=function(b){var c=$('<div class="tablerow" id="table-header" > <div class="bullet"> </div>').appendTo(b).data("level",0);$.each(a,function(){$('<div class="'+this.cellClass+' head"> </div>').appendTo(c).text(this.title)})},g=function(){var a=0;$(".tablerow").each(function(){$(this).data("level")>
a&&(a=$(this).data("level"))});$(".tablerow").each(function(){$(this).find(".name").animate({"margin-right":25*(a-$(this).data("level"))},250)})},f=function(a,b){var c=$("#row-template");b.append(Mustache.render(c.html())).children().last().css({"text-align":"center"}).text(a)},h=function(){var a=$(this),b=a.data();if(!a.hasClass("atomic"))if(a.hasClass("expanded"))a.data("childDiv").slideUp(250,function(){$(this).remove();g()}),a.find(".expand-icon").animate({"-webkit-transform":"rotate(90deg)"}),
a.removeClass("expanded");else{for(var c=$('<div class="group"></div>').insertAfter(a),d=0;d<b.sub.length;d++)k(b.sub[d],a.data("level")+1,c),a.data("childDiv",c);a.addClass("expanded");g();c.slideDown(250)}},k=function(b,c,d){var e=$("#row-template"),f=d.append(Mustache.render(e.html(),b)).children().last();f.addClass(void 0===b.sub||0===b.sub.length?"atomic":"");f.data(b);f.data("level",c);f.css({"padding-left":25*c});$.each(a,function(){var a=$('<div class="'+this.cellClass+'"> </div>').appendTo(f);
this.cellFunction?this.cellFunction(b,a.get(0)):a.text(this.value(b))});0!==b.descr.length&&f.find(".long").popover({trigger:"manual",placement:function(a,b){return 150>$(b).position().top?"bottom":"top"},content:b.descr});f.mouseenter(function(){f.find(".long").popover("show")});f.mouseleave(function(){f.find(".long").popover("hide")});f.click(h);return f};renderAmount=function(b,d){var e=b.values[yearIndex].val;a!==tables.search&&$(d).css({color:c(e)});$(d).text(formatCurrencyExact(e))};renderImpact=
function(a,b){var c=stats.impact.value(a);$(b).css({color:e(c)});$(b).text(c)};open=function(){};update=function(b){$(".tablerow").each(function(){var b=$(this);if(!b.is("#table-header"))for(var c=0;c<a.length;c++){var d=$($(b).find(".value").get(c));a[c].cellFunction?a[c].cellFunction(b.data(),d.get(0)):d.text(a[c].value(b))}})};return{initialize:function(d){var e=$("#table-container");$(".tablerow").remove();d instanceof Array?(a=tables.search,0===d.length?f("No results found.",e):(b(e),$.each(d,
function(){k(this,0,e)}))):(a=tables[avb.section],b(e),c.domain([0,0.5*d.values[yearIndex].val]),k(d,0,e).trigger("click"))},renderSparkline:function(a,b){var c=$(b).width(),d=$(b).parent().height();d3.select(b).select("svg").remove();var e=d3.select(b).append("svg").attr("width",c).attr("height",d),f=d3.scale.linear().range([0,c]).domain([avb.firstYear,avb.lastYear]),g=d3.scale.linear().range([d-2,2]).domain([0,d3.max(a.values,function(a){return a.val})]),c=d3.svg.line().interpolate("monotone").x(function(a){return f(a.year)}).y(function(a){return g(a.val)});
e.append("g").append("svg:path").classed("line",!0).attr("d",c(a.values)).style("stroke","black");e.append("g").append("svg:circle").attr("r",2).attr("cx",f(a.values[yearIndex].year)).attr("cy",g(a.values[yearIndex].val))},renderGrowth:function(a,b){var c=a.values[yearIndex-1]?a.values[yearIndex-1].val:0;perc=0===a.values[yearIndex].val?0===c?0:100:Math.round(1E4*(a.values[yearIndex].val-c)/a.values[yearIndex].val)/100;$(b).css({color:d(perc)});$(b).text(formatPercentage(perc))},renderAmount:renderAmount,
renderImpact:renderImpact,open:open,update:update}}();
